notifications:
  email: false

node_js:
 - node

install:
  - yarn

language: node_js

sudo: required

services:
  - docker

before_install:
  - docker run -dit --name emscripten -v $(pwd):/src trzeci/emscripten:sdk-incoming-64bit bash

script:
  - docker exec -it emscripten yarn test
