#!/bin/bash

build=${1:-"build"}
file=${2:-"module"}
name=$(basename "$0")
pre="pre.js"

# A absolute path to the folder containing this script.
# We need this so that it is possible to run the script from any directory.
path=$(echo "$(pwd)/$0" | sed -e "s/$name//")

test -d $path$build > /dev/null 2>&1 && rm $path$build -rf
mkdir $path$build

# Compilation
emcc "$path/main.cc" -Oz -o "$path/$build/$file.js" --pre-js "$path/$pre" \
-s WASM=1 -s NO_EXIT_RUNTIME=1 -s ALLOW_MEMORY_GROWTH=1 \
-s "EXPORTED_RUNTIME_METHODS=['cwrap', 'addOnPostRun']" \
-s "DEFAULT_LIBRARY_FUNCS_TO_INCLUDE=['malloc', 'free']"
