#!/usr/bin/env bash

echo_yellow () {
  printf "\033[33m${*}\033[0m\n"
}

throw () {
  echo $1 1>&2
  exit 1
}

if [[ -z $1 ]]; then
  throw "Pass the example folder as the first arg"
fi

# A absolute path to the folder containing this script.
# We need this so that it is possible to run the script from any directory.
cur_dir=$(echo "$(pwd)/$0" | sed -e "s/$(basename $0)//" -e "s|\./||")
example_dir=$cur_dir$(echo $1 | sed -re "s|([^/])$|\1/|" -e "s|^[./]+||")

if [[ ! -d $example_dir ]]; then
  throw "$1 is not a directory"
fi

build_dir="${example_dir}build"

test -d $build_dir > /dev/null 2>&1 && rm -rf $build_dir
mkdir -p $build_dir

echo_yellow Compiling C++...

# Compilation
emcc --bind "${example_dir}main.cc" -Oz -o "$build_dir/module.js" \
-s WASM=1 -s NO_EXIT_RUNTIME=1 -s ALLOW_MEMORY_GROWTH=1 \
-s "EXPORTED_RUNTIME_METHODS=['cwrap', 'addOnPostRun']" \
-s "DEFAULT_LIBRARY_FUNCS_TO_INCLUDE=['malloc', 'free']"

echo_yellow Done
