#!/usr/bin/env bash

echo_yellow () {
  printf "\033[1;33m${*}\033[0m\n"
}

file="module"
build="build"
name=$(basename "$0")
tempPre="_pre.js"

# Placeholder
pathPH="<%path%>"

# A absolute path to the folder containing this script.
# We need this because this script can be run from any directory.
path=$(echo "$(pwd)/$0" | sed -e "s/$name//" -e 's/\.\///')

test -d $path$build > /dev/null 2>&1 && rm -rf $path$build
mkdir $path$build

pathToMod="$path$build/"

case "$OSTYPE" in
  msys|cygwin)
    pathToMod=$(echo "$pathToMod" | sed -e 's/^\///' -e 's/\//\\\\\\\\/g' -e 's/^./\0:/');;
esac

# Substitute the placeholder with the absolute path in the `pre.js`,
# contents of which will be inserted at the beginning of the glue code.
# We need this so that the `Module` could find the .wasm file.
sed -e "s|$pathPH|$pathToMod|" < "$path/pre.js" > "$path/$tempPre"

echo_yellow Compiling C++...

# Compilation
emcc --bind "$path/main.cc" -Oz -o "$path/$build/$file.js" --pre-js "$path/$tempPre" \
-s WASM=1 -s NO_EXIT_RUNTIME=1 -s ALLOW_MEMORY_GROWTH=1 \
-s "EXPORTED_RUNTIME_METHODS=['cwrap', 'addOnPostRun']" \
-s "DEFAULT_LIBRARY_FUNCS_TO_INCLUDE=['malloc', 'free']" \
-s ENVIRONMENT=node

echo_yellow Done

rm "$path/$tempPre"
